### ISSUE TITLE
Special case letters on the webpage

### ISSUE THREAD

**Issue by marentno** [sondrebrekke/BotLer---Webpage#12]
After fixing the problem with special case letters to the database and API we opened for the lecturers to add assignments with the norwegian letters ÆØÅ (among other special characters). Unfortunately this lead to another problem where we're struggling to have the webpage print these letters.

**Comment by sondrebrekke** [comment]
Fixed 7th of april. Added the following line to the PHP-code:
$con->set_charset('utf8');
